import React, { useState, useEffect } from 'react';
import { X, Save, Plus, Trash2, Video } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { Difficulty, Scenario, VideoInput, VideoSource } from '../../types';
import VideoInputSelectorWithLibrary from '../video/VideoInputSelectorWithLibrary';
import TabNavigation, { Tab } from './TabNavigation';
import ScenarioCompetencySelector from './ScenarioCompetencySelector';
import ScenarioMetricSelector from './ScenarioMetricSelector';
import AutoGeneratedMappingsReview from './AutoGeneratedMappingsReview';
import { ScenarioTargetedCompetencyWithDetails } from '../../lib/scenarioCompetencies';
import { AutoMappingService, MetricCompetencyMatch } from '../../lib/autoMapping';
import OptionAccordion, { OptionAccordionData } from './OptionAccordion';
import { validateScenarioBeforeSave, logValidationErrors } from '../../lib/videoValidation';
import { validateSession } from '../../lib/queryHelpers';
import HierarchyLevelSelector from './HierarchyLevelSelector';
import CompetencyWeightMatrixEditor from './CompetencyWeightMatrixEditor';
import {
  getConnectionStatus,
  verifyConnectionIntegrity,
  atomicUpdateScenarioWithOptions,
  formatConnectionSummary,
  getConnectionHealthColor,
  ConnectionStatus,
  ConnectionIntegrity
} from '../../lib/connectionManager';
import { AlertCircle, Link2, AlertTriangle } from 'lucide-react';
import { CompetencyCalculationService } from '../../lib/competencyCalculation';

interface ScenarioEditModalProps {
  scenario: Scenario;
  onClose: () => void;
  onSuccess: (message: string) => void;
  onError: (message: string) => void;
}

interface Topic {
  id: string;
  title: string;
}

interface CompetencyImpact {
  impact: number;
  description?: string;
}

interface OptionForm {
  id: string;
  text: string;
  feedback_beginner: string;
  feedback_intermediate: string;
  feedback_advanced: string;
  feedback_video_beginner: VideoInput | null;
  feedback_video_intermediate: VideoInput | null;
  feedback_video_advanced: VideoInput | null;
  transition_video: VideoInput | null;
  skillImpact: { [key: string]: number };
  competency_impacts: { [competencyId: string]: CompetencyImpact };
  metricScores?: OptionMetricScoreData[];
}

const ScenarioEditModal: React.FC<ScenarioEditModalProps> = ({
  scenario,
  onClose,
  onSuccess,
  onError
}) => {
  const [activeTab, setActiveTab] = useState('introduction');
  const [loading, setLoading] = useState(false);
  const [inlineError, setInlineError] = useState<string | null>(null);
  const [topics, setTopics] = useState<Topic[]>([]);
  const [openAccordions, setOpenAccordions] = useState<number[]>([0]);

  const handleTabChange = (newTab: string) => {
    console.log(`[ScenarioEditModal] Tab changing from "${activeTab}" to "${newTab}"`);
    console.log(`[ScenarioEditModal] Current video states:`, {
      promptVideo: promptVideo ? { source: promptVideo.source, hasUrl: !!promptVideo.url, hasEmbedCode: !!promptVideo.embedCode } : null,
      optionsCount: options.length,
      optionVideos: options.map((opt, idx) => ({
        index: idx,
        feedback_beginner: opt.feedback_video_beginner ? { source: opt.feedback_video_beginner.source } : null,
        feedback_intermediate: opt.feedback_video_intermediate ? { source: opt.feedback_video_intermediate.source } : null,
        feedback_advanced: opt.feedback_video_advanced ? { source: opt.feedback_video_advanced.source } : null
      }))
    });
    setActiveTab(newTab);
  };

  const [targetedCompetencies, setTargetedCompetencies] = useState<ScenarioTargetedCompetencyWithDetails[]>([]);
  const [selectedMetricIds, setSelectedMetricIds] = useState<string[]>([]);
  const [showMappingReview, setShowMappingReview] = useState(false);
  const [mappingMatches, setMappingMatches] = useState<MetricCompetencyMatch[]>([]);
  const [isGeneratingMappings, setIsGeneratingMappings] = useState(false);
  const [connectionStatus, setConnectionStatus] = useState<ConnectionStatus | null>(null);
  const [connectionIntegrity, setConnectionIntegrity] = useState<ConnectionIntegrity | null>(null);
  const [loadingConnections, setLoadingConnections] = useState(false);
  const [connectionsToLose, setConnectionsToLose] = useState<string[]>([]);
  const [showConnectionWarning, setShowConnectionWarning] = useState(false);
  const [weightMatrix, setWeightMatrix] = useState<Record<string, Record<string, number>> | null>(null);

  const [formData, setFormData] = useState({
    title: scenario.title,
    description: scenario.description,
    topicId: scenario.topicId,
    difficulty: scenario.difficulty,
    videoPrompt: scenario.videoPrompt || '',
    isEndScenario: scenario.isEndScenario,
    isVideoRequired: scenario.isVideoRequired || false,
    timerEnabled: scenario.timerEnabled || false,
    timerVisible: scenario.timerVisible || false,
    timerDisplayLocation: scenario.timerDisplayLocation || 'hidden' as const,
    timerType: scenario.timerType || 'count_up' as const,
    timerLimitSeconds: scenario.timerLimitSeconds || 60,
    showTimerInFeedback: scenario.showTimerInFeedback !== undefined ? scenario.showTimerInFeedback : true,
    timerWarningThresholdSeconds: scenario.timerWarningThresholdSeconds || 30,
    questionText: scenario.questionText || 'How would you respond?',
  });

  const [hierarchyLevel, setHierarchyLevel] = useState<number | null>(scenario.hierarchyLevel ?? null);
  const [autoCalculateLevel, setAutoCalculateLevel] = useState<boolean>(scenario.autoCalculateLevel ?? true);
  const [isRecalculatingLevel, setIsRecalculatingLevel] = useState(false);

  const [introductionVideo, setIntroductionVideo] = useState<VideoInput>(
    scenario.introductionVideoUrl
      ? { source: 'url' as VideoSource, url: scenario.introductionVideoUrl }
      : { source: 'url' }
  );

  const [promptVideo, setPromptVideo] = useState<VideoInput>(
    scenario.promptVideoUrl
      ? { source: 'url' as VideoSource, url: scenario.promptVideoUrl }
      : { source: 'url' }
  );

  const [transitionVideo, setTransitionVideo] = useState<VideoInput>(
    scenario.transitionVideoUrl
      ? { source: 'url' as VideoSource, url: scenario.transitionVideoUrl }
      : { source: 'url' }
  );

  const [options, setOptions] = useState<OptionForm[]>(
    scenario.options.map((opt, idx) => {
      const metricScores = (opt as any).metricScores || [];

      const createVideoInput = (metadata: any, fallbackUrl?: string): VideoInput | null => {
        if (!metadata && !fallbackUrl) return null;

        if (metadata?.source && (metadata.url || metadata.embedCode || metadata.fileId || metadata.libraryId)) {
          return {
            source: metadata.source as VideoSource,
            url: metadata.url,
            embedCode: metadata.embedCode,
            fileId: metadata.fileId,
            libraryId: metadata.libraryId
          };
        }

        if (fallbackUrl) {
          return { source: 'url' as VideoSource, url: fallbackUrl };
        }

        return null;
      };

      console.log(`[ScenarioEditModal] Loading option ${idx}:`, {
        id: opt.id,
        text: opt.text?.substring(0, 30),
        metricScoresCount: metricScores.length,
        feedbackVideoMetadata: opt.feedbackVideoMetadata,
        transitionVideoMetadata: opt.transitionVideoMetadata
      });

      return {
        id: opt.id,
        text: opt.text,
        feedback_beginner: opt.feedback?.beginner || '',
        feedback_intermediate: opt.feedback?.intermediate || '',
        feedback_advanced: opt.feedback?.advanced || '',
        feedback_video_beginner: createVideoInput(opt.feedbackVideoMetadata?.beginner, opt.feedbackVideos?.beginner),
        feedback_video_intermediate: createVideoInput(opt.feedbackVideoMetadata?.intermediate, opt.feedbackVideos?.intermediate),
        feedback_video_advanced: createVideoInput(opt.feedbackVideoMetadata?.advanced, opt.feedbackVideos?.advanced),
        transition_video: createVideoInput(opt.transitionVideoMetadata, opt.transitionVideoUrl),
        skillImpact: opt.skillImpact,
        competency_impacts: opt.competency_impacts || {},
        metricScores: metricScores
      };
    })
  );

  useEffect(() => {
    loadTopics();
    loadTargetedCompetencies();
    initializeMetricsFromOptions();
    loadConnectionStatus();
  }, []);

  useEffect(() => {
    loadConnectionStatus();
  }, [scenario.id]);

  const loadConnectionStatus = async () => {
    setLoadingConnections(true);
    try {
      const status = await getConnectionStatus(scenario.id);
      if (status) {
        setConnectionStatus(status);
        console.log('[ScenarioEditModal] Connection status loaded:', status);
      }

      const integrity = await verifyConnectionIntegrity(scenario.id);
      if (integrity) {
        setConnectionIntegrity(integrity);
        console.log('[ScenarioEditModal] Connection integrity:', integrity);
      }
    } catch (error) {
      console.error('[ScenarioEditModal] Error loading connection status:', error);
    } finally {
      setLoadingConnections(false);
    }
  };

  const initializeMetricsFromOptions = () => {
    const allMetricIds = new Set<string>();
    options.forEach(opt => {
      if (opt.metricScores && opt.metricScores.length > 0) {
        opt.metricScores.forEach(ms => allMetricIds.add(ms.metricId));
      }
    });

    if (allMetricIds.size > 0) {
      setSelectedMetricIds(Array.from(allMetricIds));
      console.log('[ScenarioEditModal] Initialized metrics from options:', Array.from(allMetricIds));
    }
  };

  const loadTargetedCompetencies = async () => {
    try {
      const competencies = await ScenarioCompetencyService.getTargetedCompetencies(scenario.id);
      setTargetedCompetencies(competencies);
    } catch (error) {
      console.error('Error loading targeted competencies:', error);
    }
  };

  const loadTopics = async () => {
    try {
      const { data, error } = await supabase
        .from('topics')
        .select('id, title')
        .order('title');

      if (error) throw error;
      if (data) setTopics(data);
    } catch (error) {
      console.error('Error loading topics:', error);
      onError('Failed to load topics');
    }
  };

  const addOption = () => {
    if (options.length >= 4) {
      onError('Maximum 4 options allowed per scenario');
      return;
    }
    setOptions([...options, {
      id: `new-opt-${Date.now()}`,
      text: '',
      feedback_beginner: '',
      feedback_intermediate: '',
      feedback_advanced: '',
      feedback_video_beginner: null,
      feedback_video_intermediate: null,
      feedback_video_advanced: null,
      transition_video: null,
      skillImpact: { communication: 0 },
      competency_impacts: {},
      metricScores: []
    }]);
  };

  const removeOption = (index: number) => {
    if (options.length <= 2) {
      onError('Minimum 2 options required per scenario');
      return;
    }

    const optionToRemove = options[index];
    const hasConnection = !!optionToRemove.id && connectionStatus?.connections.some(
      c => c.optionId === optionToRemove.id && c.hasConnection
    );

    if (hasConnection) {
      const connection = connectionStatus?.connections.find(c => c.optionId === optionToRemove.id);
      const message = connection?.targetScenarioTitle
        ? `This option connects to "${connection.targetScenarioTitle}". Deleting it will break this connection. Continue?`
        : 'This option has a connection. Deleting it will break the connection. Continue?';

      if (!window.confirm(message)) {
        return;
      }
    }

    setOptions(options.filter((_, i) => i !== index));
  };

  const updateOption = (index: number, field: string, value: any) => {
    console.log(`[ScenarioEditModal] updateOption called:`, {
      index,
      field,
      value: field.includes('video') ? { source: value?.source, hasUrl: !!value?.url, hasEmbedCode: !!value?.embedCode, hasFileId: !!value?.fileId, hasLibraryId: !!value?.libraryId } : value,
      valueType: typeof value
    });

    const updated = [...options];
    if (field.includes('.')) {
      const [parent, child] = field.split('.');
      console.log(`[ScenarioEditModal] Nested field update:`, { parent, child, value });
      updated[index] = {
        ...updated[index],
        [parent]: {
          ...(updated[index] as any)[parent],
          [child]: value
        }
      };
    } else {
      console.log(`[ScenarioEditModal] Direct field update:`, { field, value });
      updated[index] = { ...updated[index], [field]: value };
    }

    if (field.includes('video')) {
      console.log(`[ScenarioEditModal] Video field updated for option ${index}:`, {
        field,
        feedback_video_beginner: updated[index].feedback_video_beginner ? { source: updated[index].feedback_video_beginner?.source, hasData: true } : null,
        feedback_video_intermediate: updated[index].feedback_video_intermediate ? { source: updated[index].feedback_video_intermediate?.source, hasData: true } : null,
        feedback_video_advanced: updated[index].feedback_video_advanced ? { source: updated[index].feedback_video_advanced?.source, hasData: true } : null,
        transition_video: updated[index].transition_video ? { source: updated[index].transition_video?.source, hasData: true } : null
      });
    }

    setOptions(updated);
  };

  const isIntroductionValid = () => {
    return formData.title.trim() !== '' &&
           formData.description.trim() !== '' &&
           formData.topicId !== '';
  };

  const isQuestionsValid = () => {
    return true;
  };

  const isOptionValid = (index: number) => {
    return options[index].text.trim() !== '' &&
           options[index].feedback_beginner.trim() !== '';
  };

  const getTabs = (): Tab[] => {
    const allOptionsValid = options.every((_, index) => isOptionValid(index));

    return [
      {
        id: 'introduction',
        label: '1. Introduction',
        isValid: isIntroductionValid(),
        isRequired: true
      },
      {
        id: 'competencies',
        label: '2. Competencies',
        isValid: targetedCompetencies.length > 0,
        isRequired: false
      },
      {
        id: 'metrics',
        label: '3. Metrics',
        isValid: selectedMetricIds.length > 0,
        isRequired: false
      },
      {
        id: 'weights',
        label: '4. Weight Matrix',
        isValid: true,
        isRequired: false
      },
      {
        id: 'questions',
        label: '5. Questions & Options',
        isValid: isQuestionsValid() && allOptionsValid,
        isRequired: true
      },
      {
        id: 'timer',
        label: '6. Decision Timer',
        isValid: true,
        isRequired: false
      }
    ];
  };

  const validateForm = () => {
    if (!formData.title.trim()) {
      onError('Please enter a scenario title');
      return false;
    }
    if (!formData.description.trim()) {
      onError('Please enter a scenario description');
      return false;
    }

    const uuidPattern = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

    for (let i = 0; i < options.length; i++) {
      if (!options[i].text.trim()) {
        onError(`Please enter text for option ${String.fromCharCode(65 + i)}`);
        return false;
      }
      if (!options[i].feedback_beginner.trim()) {
        onError(`Please enter beginner feedback for option ${String.fromCharCode(65 + i)}`);
        return false;
      }

      if (uuidPattern.test(options[i].feedback_beginner)) {
        onError(`Option ${String.fromCharCode(65 + i)} beginner feedback contains invalid data (UUID detected). Please enter proper feedback text.`);
        return false;
      }
      if (options[i].feedback_intermediate && uuidPattern.test(options[i].feedback_intermediate)) {
        onError(`Option ${String.fromCharCode(65 + i)} intermediate feedback contains invalid data (UUID detected). Please enter proper feedback text.`);
        return false;
      }
      if (options[i].feedback_advanced && uuidPattern.test(options[i].feedback_advanced)) {
        onError(`Option ${String.fromCharCode(65 + i)} advanced feedback contains invalid data (UUID detected). Please enter proper feedback text.`);
        return false;
      }
    }

    return true;
  };

  const handleSubmit = async () => {
    if (loading) return;
    if (!validateForm()) return;

    setLoading(true);
    setInlineError(null);

    const optionsSnapshot = [...options];

    try {
      const sessionCheck = await validateSession();
      if (!sessionCheck.isValid) {
        setInlineError(`Session expired: ${sessionCheck.error}. Please refresh and log in again.`);
        setLoading(false);
        return;
      }

      const scenarioToValidate = {
        ...formData,
        videoUrl: formData.videoPrompt,
        promptVideoUrl: promptVideo.url,
        introductionVideoUrl: introductionVideo.url,
        transitionVideoUrl: transitionVideo.url,
        options: options.map(opt => ({
          ...opt,
          feedback_beginner: opt.feedback_beginner,
          feedback_intermediate: opt.feedback_intermediate,
          feedback_advanced: opt.feedback_advanced,
          feedback_video_url_beginner: opt.feedback_video_beginner?.url,
          feedback_video_url_intermediate: opt.feedback_video_intermediate?.url,
          feedback_video_url_advanced: opt.feedback_video_advanced?.url,
          transitionVideoUrl: opt.transition_video?.url,
          feedbackVideoMetadata: {
            beginner: opt.feedback_video_beginner,
            intermediate: opt.feedback_video_intermediate,
            advanced: opt.feedback_video_advanced
          },
          transitionVideoMetadata: opt.transition_video
        }))
      };

      const validation = validateScenarioBeforeSave(scenarioToValidate);
      if (!validation.isValid) {
        logValidationErrors(validation.errors, 'ScenarioEditModal Validation');
        setInlineError(`Validation failed:\n${validation.errors.slice(0, 3).join('\n')}${validation.errors.length > 3 ? `\n...and ${validation.errors.length - 3} more errors` : ''}`);
        setLoading(false);
        return;
      }

      console.log('[ScenarioEditModal] Saving scenario with atomic update');
      console.log('[ScenarioEditModal] Options to save:', options.length);
      console.log('[ScenarioEditModal] Options with connections:', options.filter(o => connectionStatus?.connections.some(c => c.optionId === o.id && c.hasConnection)).length);
      console.log('[ScenarioEditModal] Question text being saved:', formData.questionText);

      const { error: scenarioError } = await supabase
        .from('scenarios')
        .update({
          title: formData.title,
          description: formData.description,
          topic_id: formData.topicId,
          difficulty: formData.difficulty,
          is_end_scenario: formData.isEndScenario,
          is_video_required: formData.isVideoRequired,
          introduction_video_url: introductionVideo.url || null,
          prompt_video_url: promptVideo.url || null,
          transition_video_url: transitionVideo.url || null,
          timer_enabled: formData.timerEnabled,
          timer_visible: formData.timerVisible,
          timer_display_location: formData.timerDisplayLocation,
          timer_type: formData.timerType,
          timer_limit_seconds: formData.timerType === 'countdown' ? formData.timerLimitSeconds : null,
          show_timer_in_feedback: formData.showTimerInFeedback,
          timer_warning_threshold_seconds: formData.timerType === 'countdown' ? formData.timerWarningThresholdSeconds : null,
          hierarchy_level: hierarchyLevel,
          auto_calculate_level: autoCalculateLevel,
          question_text: formData.questionText || 'How would you respond?',
          metadata: {
            videoPrompt: formData.videoPrompt
          },
          updated_at: new Date().toISOString()
        })
        .eq('id', scenario.id);

      if (scenarioError) {
        console.error('[ScenarioEditModal] Error saving scenario:', scenarioError);
        throw scenarioError;
      }

      console.log('[ScenarioEditModal] Scenario metadata saved successfully');

      const { data: existingOptions, error: fetchError } = await supabase
        .from('scenario_options')
        .select('id')
        .eq('scenario_id', scenario.id);

      if (fetchError) throw fetchError;

      const existingOptionIds = new Set(existingOptions?.map(o => o.id) || []);
      const currentOptionIds = new Set(options.map(o => o.id));

      const optionsToDelete = Array.from(existingOptionIds).filter(id => !currentOptionIds.has(id));

      if (optionsToDelete.length > 0) {
        console.log('[ScenarioEditModal] Deleting removed options:', optionsToDelete.length);
        const { error: deleteError } = await supabase
          .from('scenario_options')
          .delete()
          .in('id', optionsToDelete);

        if (deleteError) throw deleteError;
      }

      const optionsToUpsert = options.map((opt, index) => {
        console.log(`[ScenarioEditModal] Preparing to save option ${index}:`, {
          text: opt.text?.substring(0, 50),
          feedback_beginner: opt.feedback_beginner?.substring(0, 50),
          feedback_video_beginner: opt.feedback_video_beginner ? {
            source: opt.feedback_video_beginner.source,
            url: opt.feedback_video_beginner.url?.substring(0, 60),
            libraryId: opt.feedback_video_beginner.libraryId,
            fileId: opt.feedback_video_beginner.fileId,
            embedCode: opt.feedback_video_beginner.embedCode?.substring(0, 60)
          } : null,
          feedback_video_intermediate: opt.feedback_video_intermediate ? { source: opt.feedback_video_intermediate.source } : null,
          feedback_video_advanced: opt.feedback_video_advanced ? { source: opt.feedback_video_advanced.source } : null,
          transition_video: opt.transition_video ? { source: opt.transition_video.source } : null
        });

        const baseOption = {
          id: opt.id,
          scenario_id: scenario.id,
          option_text: opt.text,
          option_order: index,
          feedback_beginner: opt.feedback_beginner,
          feedback_intermediate: opt.feedback_intermediate || opt.feedback_beginner,
          feedback_advanced: opt.feedback_advanced || opt.feedback_beginner,
          feedback_video_url_beginner: opt.feedback_video_beginner?.url || null,
          feedback_video_url_intermediate: opt.feedback_video_intermediate?.url || null,
          feedback_video_url_advanced: opt.feedback_video_advanced?.url || null,
          feedback_video_source_beginner: opt.feedback_video_beginner?.source || null,
          feedback_video_source_intermediate: opt.feedback_video_intermediate?.source || null,
          feedback_video_source_advanced: opt.feedback_video_advanced?.source || null,
          feedback_video_library_id_beginner: opt.feedback_video_beginner?.libraryId || null,
          feedback_video_library_id_intermediate: opt.feedback_video_intermediate?.libraryId || null,
          feedback_video_library_id_advanced: opt.feedback_video_advanced?.libraryId || null,
          feedback_video_file_id_beginner: opt.feedback_video_beginner?.fileId || null,
          feedback_video_file_id_intermediate: opt.feedback_video_intermediate?.fileId || null,
          feedback_video_file_id_advanced: opt.feedback_video_advanced?.fileId || null,
          feedback_video_embed_code_beginner: opt.feedback_video_beginner?.embedCode || null,
          feedback_video_embed_code_intermediate: opt.feedback_video_intermediate?.embedCode || null,
          feedback_video_embed_code_advanced: opt.feedback_video_advanced?.embedCode || null,
          transition_video_url: opt.transition_video?.url || null,
          transition_video_source: opt.transition_video?.source || null,
          transition_video_library_id: opt.transition_video?.libraryId || null,
          transition_video_file_id: opt.transition_video?.fileId || null,
          transition_video_embed_code: opt.transition_video?.embedCode || null,
          skill_impacts: opt.skillImpact,
          competency_impacts: opt.competency_impacts
        };

        console.log(`[ScenarioEditModal] Option ${index} database payload:`, {
          feedback_video_url_beginner: baseOption.feedback_video_url_beginner,
          feedback_video_source_beginner: baseOption.feedback_video_source_beginner,
          feedback_video_library_id_beginner: baseOption.feedback_video_library_id_beginner,
          feedback_video_file_id_beginner: baseOption.feedback_video_file_id_beginner,
          feedback_video_embed_code_beginner: baseOption.feedback_video_embed_code_beginner?.substring(0, 60),
          transition_video_url: baseOption.transition_video_url,
          transition_video_source: baseOption.transition_video_source
        });

        return baseOption;
      });

      console.log(`[ScenarioEditModal] Upserting ${optionsToUpsert.length} options into database...`);

      const { data: insertedOptions, error: optionsError } = await supabase
        .from('scenario_options')
        .upsert(optionsToUpsert, { onConflict: 'id' })
        .select();

      if (optionsError) {
        console.error('[ScenarioEditModal] Error upserting options:', optionsError);
        throw optionsError;
      }

      console.log(`[ScenarioEditModal] Successfully upserted ${insertedOptions?.length || 0} options`);

      if (insertedOptions && insertedOptions.length > 0) {
        const metricScoresToInsert: any[] = [];

        insertedOptions.forEach((insertedOption, index) => {
          const optionData = options[index];
          if (optionData.metricScores && optionData.metricScores.length > 0) {
            optionData.metricScores.forEach(score => {
              metricScoresToInsert.push({
                scenario_id: scenario.id,
                option_id: insertedOption.id,
                metric_id: score.metricId,
                score_value: score.scoreValue,
                score_description: score.scoreDescription || null,
                is_primary_metric: score.isPrimaryMetric
              });
            });
          }
        });

        if (metricScoresToInsert.length > 0) {
          const { error: metricsError } = await supabase
            .from('scenario_option_metrics')
            .delete()
            .eq('scenario_id', scenario.id);

          if (metricsError) console.error('Error deleting old metrics:', metricsError);

          const { error: insertMetricsError } = await supabase
            .from('scenario_option_metrics')
            .insert(metricScoresToInsert);

          if (insertMetricsError) {
            console.error('Error inserting metric scores:', insertMetricsError);
          }
        }
      }

      try {
        const { data: syncData, error: syncError } = await supabase.rpc('sync_scenario_branches_for_scenario', {
          p_scenario_id: scenario.id
        });

        if (syncError) {
          console.error('[ScenarioEditModal] Branch sync error (non-critical):', syncError);
        } else {
          console.log('[ScenarioEditModal] Branches synced successfully', syncData);
        }
      } catch (syncError) {
        console.warn('[ScenarioEditModal] Branch sync failed (continuing):', syncError);
      }

      if (weightMatrix && Object.keys(weightMatrix).length > 0) {
        console.log('[ScenarioEditModal] Saving weight matrix...');
        const weightResult = await CompetencyCalculationService.saveScenarioWeights(
          scenario.id,
          weightMatrix
        );

        if (!weightResult.success) {
          console.error('[ScenarioEditModal] Weight save failed:', weightResult.error);
          setInlineError(`Scenario saved but weights failed: ${weightResult.error}`);
        } else {
          console.log('[ScenarioEditModal] Weight matrix saved successfully');
        }
      }

      await loadConnectionStatus();

      const expectedConnections = options.filter(o => {
        const originalOption = optionsSnapshot.find(orig => orig.id === o.id);
        return originalOption && connectionStatus?.connections.some(c => c.optionId === o.id && c.hasConnection);
      }).length;

      const actualConnections = connectionStatus?.connectedOptions || 0;

      if (expectedConnections > 0 && actualConnections < expectedConnections) {
        console.warn('[ScenarioEditModal] Connection count mismatch after save');
        setInlineError(`Warning: Some connections may not have persisted correctly. Expected ${expectedConnections}, found ${actualConnections}. Please review connections.`);
      }

      const integrity = await verifyConnectionIntegrity(scenario.id);
      if (integrity && !integrity.isValid) {
        console.warn('[ScenarioEditModal] Connection integrity issues detected:', integrity);
        setInlineError(`Warning: Connection integrity issues detected. ${integrity.orphanedConnections} orphaned connection(s). Please review.`);
      } else if (integrity) {
        console.log('[ScenarioEditModal] Connection integrity verified:', integrity);
      }

      onSuccess(`Scenario "${formData.title}" updated successfully! ${connectionStatus ? formatConnectionSummary(connectionStatus) : ''}`);
      onClose();
    } catch (error: any) {
      console.error('Error updating scenario:', error);
      const errorMessage = error.message || 'Failed to update scenario';
      setInlineError(errorMessage);
      onError(errorMessage);

      setOptions(optionsSnapshot);
      console.log('[ScenarioEditModal] Rolled back options to previous state');
    } finally {
      setLoading(false);
    }
  };

  const renderIntroductionTab = () => (
    <div className="space-y-6">
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Scenario Title *
        </label>
        <input
          type="text"
          value={formData.title}
          onChange={(e) => setFormData({ ...formData, title: e.target.value })}
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          Description *
        </label>
        <textarea
          value={formData.description}
          onChange={(e) => setFormData({ ...formData, description: e.target.value })}
          rows={4}
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Topic *
          </label>
          <select
            value={formData.topicId}
            onChange={(e) => setFormData({ ...formData, topicId: e.target.value })}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            {topics.map(topic => (
              <option key={topic.id} value={topic.id}>{topic.title}</option>
            ))}
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Difficulty *
          </label>
          <select
            value={formData.difficulty}
            onChange={(e) => setFormData({ ...formData, difficulty: e.target.value as Difficulty })}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          >
            <option value="beginner">Beginner</option>
            <option value="intermediate">Intermediate</option>
            <option value="advanced">Advanced</option>
          </select>
        </div>
      </div>

      <div className="border-t pt-4">
        <VideoInputSelectorWithLibrary
          label="Introduction Video"
          value={introductionVideo}
          onChange={setIntroductionVideo}
          videoType="introduction"
          helpText="Video shown first to introduce the scenario"
          filterByTopic={formData.topicId}
          scenarioName={formData.title}
          scenarioDifficulty={formData.difficulty}
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          <Video className="inline w-4 h-4 mr-1" />
          Video Prompt (Optional)
        </label>
        <textarea
          value={formData.videoPrompt}
          onChange={(e) => setFormData({ ...formData, videoPrompt: e.target.value })}
          rows={3}
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Describe what the AI presenter should say..."
        />
      </div>

      <div className="border-t pt-4">
        <HierarchyLevelSelector
          value={hierarchyLevel}
          autoCalculate={autoCalculateLevel}
          calculatedLevel={scenario.hierarchyLevel}
          onChange={setHierarchyLevel}
          onAutoCalculateChange={(auto) => {
            setAutoCalculateLevel(auto);
            if (auto && scenario.hierarchyLevel !== null && scenario.hierarchyLevel !== undefined) {
              setHierarchyLevel(scenario.hierarchyLevel);
            }
          }}
          onRecalculate={async () => {
            setIsRecalculatingLevel(true);
            try {
              const { data, error } = await supabase.rpc('apply_scenario_hierarchy_levels');
              if (error) throw error;

              const { data: updatedScenario, error: fetchError } = await supabase
                .from('scenarios')
                .select('hierarchy_level')
                .eq('id', scenario.id)
                .single();

              if (fetchError) throw fetchError;
              if (updatedScenario) {
                setHierarchyLevel(updatedScenario.hierarchy_level);
              }
            } catch (error) {
              console.error('Error recalculating hierarchy levels:', error);
              onError('Failed to recalculate hierarchy levels');
            } finally {
              setIsRecalculatingLevel(false);
            }
          }}
          isRecalculating={isRecalculatingLevel}
          showAutoToggle={true}
        />
      </div>

      <div className="space-y-2">
        <div className="flex items-center">
          <input
            type="checkbox"
            id="isEndScenario"
            checked={formData.isEndScenario}
            onChange={(e) => setFormData({ ...formData, isEndScenario: e.target.checked })}
            className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
          />
          <label htmlFor="isEndScenario" className="ml-2 block text-sm text-gray-700">
            This is an end scenario (shows results summary)
          </label>
        </div>
        <div className="flex items-center">
          <input
            type="checkbox"
            id="isVideoRequired"
            checked={formData.isVideoRequired}
            onChange={(e) => setFormData({ ...formData, isVideoRequired: e.target.checked })}
            className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
          />
          <label htmlFor="isVideoRequired" className="ml-2 block text-sm text-gray-700">
            Require videos to be watched (production mode)
          </label>
        </div>
      </div>
    </div>
  );

  const handleCompetenciesChanged = async (competencies: ScenarioTargetedCompetencyWithDetails[]) => {
    setTargetedCompetencies(competencies);
    if (competencies.length > 0 && selectedMetricIds.length > 0) {
      await handleAutoGenerateMappings(selectedMetricIds);
    }
  };

  const handleMetricsChanged = async (metricIds: string[]) => {
    setSelectedMetricIds(metricIds);
    if (metricIds.length > 0 && targetedCompetencies.length > 0) {
      await handleAutoGenerateMappings(metricIds);
    }
  };

  const handleAutoGenerateMappings = async (metricIds: string[]) => {
    setIsGeneratingMappings(true);
    try {
      const matches = await AutoMappingService.previewMappings(scenario.id, metricIds);
      setMappingMatches(matches);
      if (matches.length > 0) {
        setShowMappingReview(true);
      }
    } catch (error) {
      console.error('Error previewing mappings:', error);
      onError('Failed to generate mapping preview');
    } finally {
      setIsGeneratingMappings(false);
    }
  };

  const handleAcceptMappings = async () => {
    if (!scenario.simulation_id) {
      onError('Simulation ID is required for auto-mapping');
      return;
    }

    setIsGeneratingMappings(true);
    try {
      const result = await AutoMappingService.autoGenerateMappings(
        scenario.id,
        scenario.simulation_id,
        selectedMetricIds
      );

      if (result.created > 0) {
        onSuccess(`Created ${result.created} automatic mapping${result.created !== 1 ? 's' : ''}!`);
        if (result.skipped > 0) {
          onSuccess(`Skipped ${result.skipped} existing mapping${result.skipped !== 1 ? 's' : ''}`);
        }
      }

      if (result.errors.length > 0) {
        result.errors.forEach(err => onError(err));
      }

      setShowMappingReview(false);
      setMappingMatches([]);
    } catch (error) {
      console.error('Error creating mappings:', error);
      onError('Failed to create automatic mappings');
    } finally {
      setIsGeneratingMappings(false);
    }
  };

  const renderCompetenciesTab = () => (
    <div className="space-y-6">
      <div className="bg-blue-50 border border-blue-200 rounded-md p-4">
        <h4 className="font-medium text-blue-900 mb-2">Scenario Context</h4>
        <p className="text-sm text-blue-800"><strong>Title:</strong> {formData.title || 'Not set'}</p>
        <p className="text-sm text-blue-800 mt-1"><strong>Description:</strong> {formData.description || 'Not set'}</p>
      </div>

      <ScenarioCompetencySelector
        scenarioId={scenario.id}
        onCompetenciesChanged={handleCompetenciesChanged}
      />
    </div>
  );

  const renderMetricsTab = () => (
    <div className="space-y-6">
      <div className="bg-blue-50 border border-blue-200 rounded-md p-4">
        <h4 className="font-medium text-blue-900 mb-2">Target Competencies</h4>
        {targetedCompetencies.length === 0 ? (
          <p className="text-sm text-blue-800">No competencies targeted yet. Go to the Competencies tab to select target competencies.</p>
        ) : (
          <div className="flex flex-wrap gap-2">
            {targetedCompetencies.map(comp => (
              <span key={comp.id} className="text-xs px-2 py-1 bg-blue-100 text-blue-800 rounded">
                {comp.competency_code} - {comp.competency_name}
              </span>
            ))}
          </div>
        )}
      </div>

      <ScenarioMetricSelector
        selectedMetricIds={selectedMetricIds}
        onMetricsChange={handleMetricsChanged}
      />

      {showMappingReview && (
        <div className="border-t pt-6">
          <AutoGeneratedMappingsReview
            matches={mappingMatches}
            onAccept={handleAcceptMappings}
            onCancel={() => {
              setShowMappingReview(false);
              setMappingMatches([]);
            }}
            isGenerating={isGeneratingMappings}
          />
        </div>
      )}
    </div>
  );

  const toggleAccordion = (index: number) => {
    setOpenAccordions(prev =>
      prev.includes(index)
        ? prev.filter(i => i !== index)
        : [...prev, index]
    );
  };

  const renderQuestionsTab = () => (
    <div className="space-y-6">
      <div className="bg-blue-50 border border-blue-200 rounded-md p-4">
        <h4 className="font-medium text-blue-900 mb-2">Scenario Context</h4>
        <p className="text-sm text-blue-800"><strong>Title:</strong> {formData.title || 'Not set'}</p>
        <p className="text-sm text-blue-800 mt-1"><strong>Description:</strong> {formData.description || 'Not set'}</p>
      </div>

      <div>
        <VideoInputSelectorWithLibrary
          label="Prompt Video"
          value={promptVideo}
          onChange={setPromptVideo}
          videoType="prompt"
          helpText="Video shown after introduction with scenario details"
          filterByTopic={formData.topicId}
          scenarioName={formData.title}
          scenarioDifficulty={formData.difficulty}
        />
      </div>

      <div className="border-t pt-4">
        <VideoInputSelectorWithLibrary
          label="Transition Video (Optional)"
          value={transitionVideo}
          onChange={setTransitionVideo}
          videoType="transition"
          helpText="Default video shown when transitioning to next scenario (can be overridden per option)"
          filterByTopic={formData.topicId}
          scenarioName={formData.title}
          scenarioDifficulty={formData.difficulty}
        />
      </div>

      <div className="border-t pt-4">
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Question Text *
          </label>
          <input
            type="text"
            value={formData.questionText}
            onChange={(e) => setFormData({ ...formData, questionText: e.target.value })}
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            placeholder="How would you respond?"
          />
          <p className="mt-1 text-xs text-gray-500">
            This question will be displayed to learners before they see the response options.
          </p>
        </div>
      </div>

      <div className="border-t pt-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Response Options</h3>
            <p className="text-sm text-gray-600 mt-1">
              Configure {options.length} option{options.length !== 1 ? 's' : ''} (minimum 2, maximum 4)
            </p>
          </div>
          {options.length < 4 && (
            <button
              onClick={addOption}
              className="inline-flex items-center px-3 py-2 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors"
            >
              <Plus className="w-4 h-4 mr-1" />
              Add Option {String.fromCharCode(65 + options.length)}
            </button>
          )}
        </div>

        <div className="space-y-3">
          {options.map((option, index) => {
            const connection = connectionStatus?.connections.find(c => c.optionId === option.id);
            const connectionInfo = connection ? {
              hasConnection: connection.hasConnection,
              targetTitle: connection.targetTitle,
              targetScenarioId: connection.nextScenarioId || undefined
            } : undefined;

            return (
              <OptionAccordion
                key={option.id}
                option={option}
                index={index}
                isOpen={openAccordions.includes(index)}
                onToggle={() => toggleAccordion(index)}
                onChange={(field, value) => updateOption(index, field, value)}
                onRemove={options.length > 2 ? () => removeOption(index) : undefined}
                canRemove={options.length > 2}
                selectedMetricIds={selectedMetricIds}
                topicId={formData.topicId}
                scenarioTitle={formData.title}
                scenarioDifficulty={formData.difficulty}
                isEditMode={true}
                simulationId={scenario.simulation_id}
                scenarioId={scenario.id}
                connectionInfo={connectionInfo}
              />
            );
          })}
        </div>
      </div>
    </div>
  );


  const renderTimerTab = () => {
    return (
      <div className="space-y-6">
        <div>
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">Decision Timer Configuration</h3>
          <p className="text-sm text-gray-600 mb-6">
            Configure how decision time is tracked and displayed to learners. This helps analyze decision-making speed and add time pressure when needed.
          </p>
        </div>

        <div className="space-y-4">
          <div className="flex items-center">
            <input
              type="checkbox"
              id="timerEnabled"
              checked={formData.timerEnabled}
              onChange={(e) => setFormData({ ...formData, timerEnabled: e.target.checked })}
              className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
            />
            <label htmlFor="timerEnabled" className="ml-2 block text-sm font-medium text-gray-700">
              Enable decision time tracking
            </label>
          </div>

          {formData.timerEnabled && (
            <>
              <div className="flex items-center">
                <input
                  type="checkbox"
                  id="timerVisible"
                  checked={formData.timerVisible}
                  onChange={(e) => setFormData({ ...formData, timerVisible: e.target.checked })}
                  className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                />
                <label htmlFor="timerVisible" className="ml-2 block text-sm font-medium text-gray-700">
                  Make timer visible to learners
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Timer Type
                </label>
                <select
                  value={formData.timerType}
                  onChange={(e) => setFormData({ ...formData, timerType: e.target.value as 'count_up' | 'countdown' | 'none' })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="count_up">Count Up - Shows elapsed time</option>
                  <option value="countdown">Countdown - Creates time pressure</option>
                  <option value="none">None - Track silently without display</option>
                </select>
              </div>

              {formData.timerType === 'countdown' && (
                <>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Time Limit (seconds)
                    </label>
                    <input
                      type="number"
                      min="10"
                      max="600"
                      value={formData.timerLimitSeconds}
                      onChange={(e) => setFormData({ ...formData, timerLimitSeconds: parseInt(e.target.value) || 60 })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Recommended: 30-120 seconds for most scenarios
                    </p>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Warning Threshold (seconds)
                    </label>
                    <input
                      type="number"
                      min="5"
                      max="60"
                      value={formData.timerWarningThresholdSeconds}
                      onChange={(e) => setFormData({ ...formData, timerWarningThresholdSeconds: parseInt(e.target.value) || 30 })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    />
                    <p className="text-xs text-gray-500 mt-1">
                      Timer will change color when time remaining reaches this threshold
                    </p>
                  </div>
                </>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Display Location
                </label>
                <select
                  value={formData.timerDisplayLocation}
                  onChange={(e) => setFormData({ ...formData, timerDisplayLocation: e.target.value as any })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                >
                  <option value="hidden">Hidden - Track only, don't display</option>
                  <option value="question_page">Question Page - Show during decision</option>
                  <option value="feedback_page">Feedback Page - Show after decision</option>
                  <option value="results_page">Results Page - Show in final summary</option>
                  <option value="all">All Locations - Show everywhere</option>
                </select>
              </div>

              <div className="flex items-center">
                <input
                  type="checkbox"
                  id="showTimerInFeedback"
                  checked={formData.showTimerInFeedback}
                  onChange={(e) => setFormData({ ...formData, showTimerInFeedback: e.target.checked })}
                  className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                />
                <label htmlFor="showTimerInFeedback" className="ml-2 block text-sm font-medium text-gray-700">
                  Include decision time insights in feedback
                </label>
              </div>
            </>
          )}
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h4 className="text-sm font-semibold text-blue-900 mb-2">Timer Benefits</h4>
          <ul className="text-sm text-blue-800 space-y-1">
            <li>• Track how long learners take to make decisions</li>
            <li>• Analyze decision-making patterns across cohorts</li>
            <li>• Add time pressure for high-stakes scenarios</li>
            <li>• Provide personalized feedback based on decision speed</li>
            <li>• Decision time is always tracked for analytics, regardless of visibility</li>
          </ul>
        </div>
      </div>
    );
  };

  const renderWeightsTab = () => (
    <div className="space-y-6">
      <CompetencyWeightMatrixEditor
        scenarioId={scenario.id}
        simulationId={formData.topicId}
        showInheritanceInfo={true}
        readOnly={false}
        onWeightsChange={(weights) => {
          console.log('[ScenarioEditModal] Weights changed:', Object.keys(weights).length, 'competencies');
          setWeightMatrix(weights);
        }}
      />
    </div>
  );

  const renderActiveTab = () => {
    if (activeTab === 'introduction') return renderIntroductionTab();
    if (activeTab === 'competencies') return renderCompetenciesTab();
    if (activeTab === 'metrics') return renderMetricsTab();
    if (activeTab === 'weights') return renderWeightsTab();
    if (activeTab === 'questions') return renderQuestionsTab();
    if (activeTab === 'timer') return renderTimerTab();
    return null;
  };

  const goToPreviousTab = () => {
    const tabs = getTabs();
    const currentIndex = tabs.findIndex(t => t.id === activeTab);
    if (currentIndex > 0) {
      handleTabChange(tabs[currentIndex - 1].id);
    }
  };

  const goToNextTab = () => {
    const tabs = getTabs();
    const currentIndex = tabs.findIndex(t => t.id === activeTab);
    if (currentIndex < tabs.length - 1) {
      handleTabChange(tabs[currentIndex + 1].id);
    }
  };

  const isLastTab = () => {
    const tabs = getTabs();
    const currentIndex = tabs.findIndex(t => t.id === activeTab);
    return currentIndex === tabs.length - 1;
  };

  const isFirstTab = () => {
    return activeTab === 'introduction';
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
          <div className="flex-1">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Edit Scenario</h2>
            <p className="text-sm text-gray-500 mt-1">{scenario.title}</p>
            {connectionStatus && (
              <div className="flex items-center gap-2 mt-2">
                <Link2 className="w-4 h-4 text-gray-400 dark:text-gray-500" />
                <span className="text-sm text-gray-600">
                  {formatConnectionSummary(connectionStatus)}
                </span>
                {connectionStatus.connectedOptions > 0 && (
                  <span className={`px-2 py-1 text-xs rounded-full ${
                    getConnectionHealthColor(connectionStatus) === 'green' ? 'bg-green-100 text-green-700' :
                    getConnectionHealthColor(connectionStatus) === 'yellow' ? 'bg-yellow-100 text-yellow-700' :
                    getConnectionHealthColor(connectionStatus) === 'orange' ? 'bg-orange-100 text-orange-700' :
                    'bg-red-100 text-red-700'
                  }`}>
                    {connectionStatus.connectedOptions} connected
                  </span>
                )}
                {loadingConnections && (
                  <span className="text-xs text-gray-400 dark:text-gray-500 animate-pulse">Checking...</span>
                )}
              </div>
            )}
            {connectionIntegrity && !connectionIntegrity.isValid && (
              <div className="flex items-center gap-2 mt-1">
                <AlertTriangle className="w-4 h-4 text-orange-500" />
                <span className="text-xs text-orange-600">
                  Connection integrity warning: {connectionIntegrity.orphanedConnections} issue(s) detected
                </span>
              </div>
            )}
          </div>
          <button onClick={onClose} className="text-gray-400 dark:text-gray-500 hover:text-gray-600">
            <X className="w-6 h-6" />
          </button>
        </div>

        <TabNavigation
          tabs={getTabs()}
          activeTab={activeTab}
          onTabChange={handleTabChange}
        />

        <div className="px-6 py-6 overflow-y-auto flex-1">
          {inlineError && (
            <div className="mb-4 bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="flex items-start">
                <div className="flex-shrink-0">
                  <X className="h-5 w-5 text-red-400" />
                </div>
                <div className="ml-3 flex-1">
                  <h3 className="text-sm font-medium text-red-800">Error</h3>
                  <p className="text-sm text-red-700 mt-1">{inlineError}</p>
                </div>
                <button
                  onClick={() => setInlineError(null)}
                  className="ml-3 text-red-400 hover:text-red-600"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
            </div>
          )}
          {renderActiveTab()}
        </div>

        <div className="px-6 py-4 border-t border-gray-200 dark:border-gray-700">
          <div className="flex justify-between">
            <button
              onClick={isFirstTab() ? onClose : goToPreviousTab}
              className="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200"
            >
              {isFirstTab() ? 'Cancel' : 'Previous'}
            </button>

            <div className="flex gap-2">
              {!isLastTab() ? (
                <button
                  onClick={goToNextTab}
                  className="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                >
                  Next
                </button>
              ) : (
                <button
                  onClick={handleSubmit}
                  disabled={loading}
                  className="inline-flex items-center px-6 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
                >
                  <Save className="w-4 h-4 mr-2" />
                  {loading ? 'Saving...' : 'Save Changes'}
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ScenarioEditModal;
