'use client';

import React, { useState } from 'react';
import { AlertTriangle, CheckCircle, Info, Sparkles, TrendingUp, Zap } from 'lucide-react';
import { MetricCompetencyMatch } from '@/lib/autoMapping';

interface AutoGeneratedMappingsReviewProps {
  matches: MetricCompetencyMatch[];
  onAccept: () => void;
  onCancel: () => void;
  isGenerating?: boolean;
}

const AutoGeneratedMappingsReview: React.FC<AutoGeneratedMappingsReviewProps> = ({
  matches,
  onAccept,
  onCancel,
  isGenerating = false
}) => {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  const getConfidenceColor = (confidence: string): string => {
    const colors: Record<string, string> = {
      high: 'bg-green-100 text-green-800',
      medium: 'bg-yellow-100 text-yellow-800',
      low: 'bg-orange-100 text-orange-800'
    };
    return colors[confidence] || 'bg-gray-100 text-gray-800 dark:text-gray-100';
  };

  const getConfidenceIcon = (confidence: string) => {
    if (confidence === 'high') return <CheckCircle className="w-4 h-4 text-green-600" />;
    if (confidence === 'medium') return <Info className="w-4 h-4 text-yellow-600" />;
    return <AlertTriangle className="w-4 h-4 text-orange-600" />;
  };

  const getMethodColor = (method: string): string => {
    const colors: Record<string, string> = {
      linear: 'bg-blue-100 text-blue-800',
      threshold_based: 'bg-green-100 text-green-800',
      exponential_growth: 'bg-purple-100 text-purple-800',
      compensatory: 'bg-yellow-100 text-yellow-800',
      conjunctive: 'bg-red-100 text-red-800'
    };
    return colors[method] || 'bg-gray-100 text-gray-800 dark:text-gray-100';
  };

  const highConfidenceCount = matches.filter(m => m.confidence === 'high').length;
  const mediumConfidenceCount = matches.filter(m => m.confidence === 'medium').length;
  const lowConfidenceCount = matches.filter(m => m.confidence === 'low').length;

  const uniqueMetrics = new Set(matches.map(m => m.metric_id)).size;
  const uniqueCompetencies = new Set(matches.map(m => m.competency_id)).size;

  if (isGenerating) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-8">
        <div className="flex flex-col items-center justify-center">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-600 mb-4"></div>
          <p className="text-sm text-gray-600">Analyzing metrics and competencies...</p>
          <p className="text-xs text-gray-500 mt-1">Generating intelligent mappings</p>
        </div>
      </div>
    );
  }

  if (matches.length === 0) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-8">
        <div className="flex flex-col items-center justify-center text-center">
          <AlertTriangle className="w-12 h-12 text-orange-500 mb-4" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
            No Mappings Generated
          </h3>
          <p className="text-sm text-gray-600 max-w-md">
            Unable to generate automatic mappings. Please ensure you have both metrics and targeted
            competencies selected.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="bg-gradient-to-r from-blue-50 to-green-50 rounded-lg border border-blue-200 p-4">
        <div className="flex items-start gap-3">
          <Sparkles className="w-6 h-6 text-blue-600 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <h3 className="text-base font-semibold text-gray-900 dark:text-gray-100 mb-1">
              Automatic Mappings Generated
            </h3>
            <p className="text-sm text-gray-700 mb-3">
              We've intelligently mapped {uniqueMetrics} metric{uniqueMetrics !== 1 ? 's' : ''} to
              {uniqueCompetencies} competenc{uniqueCompetencies !== 1 ? 'ies' : ''}, creating
              {matches.length} mapping{matches.length !== 1 ? 's' : ''}.
            </p>
            <div className="grid grid-cols-3 gap-2">
              <div className="bg-white dark:bg-gray-800 rounded p-2 border border-green-200">
                <div className="flex items-center gap-1 mb-1">
                  <CheckCircle className="w-3 h-3 text-green-600" />
                  <span className="text-xs font-medium text-gray-700">High Confidence</span>
                </div>
                <span className="text-lg font-bold text-green-600">{highConfidenceCount}</span>
              </div>
              <div className="bg-white dark:bg-gray-800 rounded p-2 border border-yellow-200">
                <div className="flex items-center gap-1 mb-1">
                  <Info className="w-3 h-3 text-yellow-600" />
                  <span className="text-xs font-medium text-gray-700">Medium Confidence</span>
                </div>
                <span className="text-lg font-bold text-yellow-600">{mediumConfidenceCount}</span>
              </div>
              <div className="bg-white dark:bg-gray-800 rounded p-2 border border-orange-200">
                <div className="flex items-center gap-1 mb-1">
                  <AlertTriangle className="w-3 h-3 text-orange-600" />
                  <span className="text-xs font-medium text-gray-700">Low Confidence</span>
                </div>
                <span className="text-lg font-bold text-orange-600">{lowConfidenceCount}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700">
        <div className="px-4 py-3 border-b border-gray-200 dark:border-gray-700 bg-gray-50">
          <h4 className="text-sm font-semibold text-gray-900 dark:text-gray-100 flex items-center gap-2">
            <Zap className="w-4 h-4" />
            Proposed Mappings
          </h4>
          <p className="text-xs text-gray-600 mt-0.5">
            Review the generated mappings below. Click on any mapping to see details.
          </p>
        </div>

        <div className="divide-y divide-gray-200 max-h-96 overflow-y-auto">
          {matches.map((match, index) => (
            <div
              key={`${match.metric_id}-${match.competency_id}-${index}`}
              className="p-3 hover:bg-gray-50 transition-colors cursor-pointer"
              onClick={() => setExpandedIndex(expandedIndex === index ? null : index)}
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    {getConfidenceIcon(match.confidence)}
                    <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
                      {match.metric_name}
                    </span>
                    <span className="text-gray-400 dark:text-gray-500">→</span>
                    <span className="text-sm font-medium text-blue-600">
                      {match.competency_name}
                    </span>
                  </div>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className={`text-xs px-2 py-0.5 rounded ${getConfidenceColor(match.confidence)}`}>
                      {match.confidence} confidence
                    </span>
                    <span className={`text-xs px-2 py-0.5 rounded ${getMethodColor(match.calculation_method)}`}>
                      {match.calculation_method.replace('_', ' ')}
                    </span>
                    <span className="text-xs text-gray-600 flex items-center gap-1">
                      <TrendingUp className="w-3 h-3" />
                      Weight: {(match.mapping_weight * 100).toFixed(0)}%
                    </span>
                  </div>
                </div>
              </div>

              {expandedIndex === index && (
                <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 -mx-3 px-3 py-2">
                  <div className="space-y-2">
                    <div>
                      <span className="text-xs font-medium text-gray-700">Metric Type:</span>
                      <span className="text-xs text-gray-600 ml-2">
                        {match.metric_type.replace('_', ' ')}
                      </span>
                    </div>
                    <div>
                      <span className="text-xs font-medium text-gray-700">Competency Code:</span>
                      <span className="text-xs text-gray-600 ml-2">{match.competency_code}</span>
                    </div>
                    <div>
                      <span className="text-xs font-medium text-gray-700 block mb-1">Rationale:</span>
                      <p className="text-xs text-gray-600 italic">{match.rationale}</p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
        <div className="flex items-start gap-2">
          <Info className="w-4 h-4 text-blue-600 flex-shrink-0 mt-0.5" />
          <div className="flex-1 text-xs text-blue-800">
            <p className="font-medium mb-1">About Automatic Mappings</p>
            <ul className="space-y-0.5 ml-4 list-disc">
              <li>High confidence mappings are direct metric-to-competency matches</li>
              <li>Medium confidence mappings have supporting relationships</li>
              <li>Low confidence mappings may need manual review and adjustment</li>
              <li>You can edit these mappings later in the Mapping Manager</li>
            </ul>
          </div>
        </div>
      </div>

      <div className="flex justify-end gap-3 pt-2">
        <button
          onClick={onCancel}
          className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
        >
          Cancel
        </button>
        <button
          onClick={onAccept}
          className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700 flex items-center gap-2"
        >
          <CheckCircle className="w-4 h-4" />
          Accept & Create {matches.length} Mapping{matches.length !== 1 ? 's' : ''}
        </button>
      </div>
    </div>
  );
};

export default AutoGeneratedMappingsReview;
